import assets from "./assets";

const NFTData = [
  {
    id: "CH011",
    name: "Chambre La Belle Etoile",
    creator: "Olive du Bois",
    price: 90.25,
    description:
      "La vie est belle. Il est bon de passer ses vacances a la BELLE.",
    image: assets.ch011,
    RESERVs: [
      {
        id: "RESERV-011",
        name: "Codjo Le Prince",
        price: 84.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-01112",
        name: "Fabrice Du Mont",
        price: 94.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-13",
        name: "Jackie Wong",
        price: 88.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CU011",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu011,
    RESERVs: [
      {
        id: "RESERV-01121",
        name: "Codjo Le Prince",
        price: 7.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO011",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 95.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do011,
    RESERVs: [
      {
        id: "RESERV-01131",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-01132",
        name: "Fabrice Du Mont",
        price: 95.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "JA011",
    name: "Jardin Dargent",
    creator: "Olivie du Bois",
    price: 54.25,
    description:
      "Le jardin des ancetres. Une representation de lheritage glorieux de ceux qui ont batti le present",
    image: assets.ja011,
    RESERVs: [
      {
        id: "RESERV-01141",
        name: "Codjo Le Prince",
        price: 56.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-01142",
        name: "Fabrice Du Mont",
        price: 54.25,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-01143",
        name: "Jackie Wong",
        price: 55.15,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-01144",
        name: "Vincent Swift",
        price: 54.15,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "PI011",
    name: "Piscine Des Orca",
    creator: "David Au Bon",
    price: 10.25,
    description:
      "La piscine du Chateau deau qui vous rappelle vos reves les plus beaux",
    image: assets.pi011,
    RESERVs: [
      {
        id: "RESERV-51",
        name: "Codjo Le Prince",
        price: 20.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "SA011",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 20.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa011,
    RESERVs: [
      {
        id: "RESERV-61",
        name: "Codjo Le Prince",
        price: 29.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-62",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-63",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-64",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-65",
        name: "Caroline Lee",
        price: 17.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH022",
    name: "Chambre Des Grands",
    creator: "Fabien Le Patient",
    price: 58.25,
    description:
      "La chambre assortit de tous les accessoirs pour un agreable repos et haute consideration du temps passe durant tout le sejour",
    image: assets.ch022,
    RESERVs: [],
  },
  {
    id: "CU022",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu022,
    RESERVs: [
      {
        id: "RESERV-02221",
        name: "Codjo Le Prince",
        price: 97.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO022",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 195.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do022,
    RESERVs: [
      {
        id: "RESERV-02231",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-02232",
        name: "Fabrice Du Mont",
        price: 45.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "JA022",
    name: "Jardin Dargent",
    creator: "Olivie du Bois",
    price: 34.25,
    description:
      "Le jardin des ancetres. Une representation de lheritage glorieux de ceux qui ont batti le present",
    image: assets.ja022,
    RESERVs: [
      {
        id: "RESERV-02241",
        name: "Codjo Le Prince",
        price: 56.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-02242",
        name: "Fabrice Du Mont",
        price: 24.25,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-02243",
        name: "Jackie Wong",
        price: 15.15,
        image: assets.person04,
        date: "Decembre 01, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-02244",
        name: "Vincent Swift",
        price: 9.15,
        image: assets.person02,
        date: "Decembre 21, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "PI022",
    name: "Piscine Des Orca",
    creator: "David Au Bon",
    price: 19.25,
    description:
      "La piscine du Chateau deau qui vous rappelle vos reves les plus beaux",
    image: assets.pi022,
    RESERVs: [
      {
        id: "RESERV-51",
        name: "Jean Le Cool",
        price: 20.25,
        image: assets.person02,
        date: "Janvier 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "SA022",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 29.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa022,
    RESERVs: [
      {
        id: "RESERV-61",
        name: "Codjo Le Prince",
        price: 39.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-62",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-63",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-64",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Novembre 11, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-65",
        name: "Caroline Lee",
        price: 37.25,
        image: assets.person02,
        date: "Decembre 17, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH033",
    name: "Chambre La Belle Etoile",
    creator: "Olive du Bois",
    price: 90.25,
    description:
      "La vie est belle. Il est bon de passer ses vacances a la BELLE.",
    image: assets.ch033,
    RESERVs: [
      {
        id: "RESERV-033",
        name: "Codjo Le Prince",
        price: 84.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-03312",
        name: "Fabrice Du Mont",
        price: 94.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-13",
        name: "Jackie Wong",
        price: 88.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CU033",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu033,
    RESERVs: [
      {
        id: "RESERV-03321",
        name: "Codjo Le Prince",
        price: 7.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO033",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 95.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do033,
    RESERVs: [
      {
        id: "RESERV-03331",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-03332",
        name: "Fabrice Du Mont",
        price: 95.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "JA033",
    name: "Jardin Dargent",
    creator: "Olivie du Bois",
    price: 54.25,
    description:
      "Le jardin des ancetres. Une representation de lheritage glorieux de ceux qui ont batti le present",
    image: assets.ja033,
    RESERVs: [
      {
        id: "RESERV-03341",
        name: "Codjo Le Prince",
        price: 56.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-03342",
        name: "Fabrice Du Mont",
        price: 54.25,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-03343",
        name: "Jackie Wong",
        price: 55.15,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-03344",
        name: "Vincent Swift",
        price: 54.15,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "PI033",
    name: "Piscine Des Orca",
    creator: "David Au Bon",
    price: 10.25,
    description:
      "La piscine du Chateau deau qui vous rappelle vos reves les plus beaux",
    image: assets.pi033,
    RESERVs: [
      {
        id: "RESERV-03351",
        name: "Codjo Le Prince",
        price: 20.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "SA033",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 20.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa033,
    RESERVs: [
      {
        id: "RESERV-61",
        name: "Codjo Le Prince",
        price: 29.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-62",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-63",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-64",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-65",
        name: "Caroline Lee",
        price: 17.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH044",
    name: "Chambre Des Grands",
    creator: "Fabien Le Patient",
    price: 58.25,
    description:
      "La chambre assortit de tous les accessoirs pour un agreable repos et haute consideration du temps passe durant tout le sejour",
    image: assets.ch044,
    RESERVs: [],
  },
  {
    id: "CU044",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu044,
    RESERVs: [
      {
        id: "RESERV-04421",
        name: "Codjo Le Prince",
        price: 97.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO044",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 195.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do044,
    RESERVs: [
      {
        id: "RESERV-04431",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-04432",
        name: "Fabrice Du Mont",
        price: 45.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "JA044",
    name: "Jardin Dargent",
    creator: "Olivie du Bois",
    price: 34.25,
    description:
      "Le jardin des ancetres. Une representation de lheritage glorieux de ceux qui ont batti le present",
    image: assets.ja044,
    RESERVs: [
      {
        id: "RESERV-04441",
        name: "Codjo Le Prince",
        price: 56.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-04442",
        name: "Fabrice Du Mont",
        price: 24.25,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-04443",
        name: "Jackie Wong",
        price: 15.15,
        image: assets.person04,
        date: "Decembre 01, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-04444",
        name: "Vincent Swift",
        price: 9.15,
        image: assets.person02,
        date: "Decembre 21, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "PI044",
    name: "Piscine Des Orca",
    creator: "David Au Bon",
    price: 19.25,
    description:
      "La piscine du Chateau deau qui vous rappelle vos reves les plus beaux",
    image: assets.pi044,
    RESERVs: [
      {
        id: "RESERV-04451",
        name: "Jean Le Cool",
        price: 20.25,
        image: assets.person02,
        date: "Janvier 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "SA044",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 29.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa044,
    RESERVs: [
      {
        id: "RESERV-04461",
        name: "Codjo Le Prince",
        price: 39.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-04462",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-04463",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-04464",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Novembre 11, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-04465",
        name: "Caroline Lee",
        price: 37.25,
        image: assets.person02,
        date: "Decembre 17, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH055",
    name: "Chambre La Belle Etoile",
    creator: "Olive du Bois",
    price: 90.25,
    description:
      "La vie est belle. Il est bon de passer ses vacances a la BELLE.",
    image: assets.ch055,
    RESERVs: [
      {
        id: "RESERV-055",
        name: "Codjo Le Prince",
        price: 84.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-05512",
        name: "Fabrice Du Mont",
        price: 94.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-13",
        name: "Jackie Wong",
        price: 88.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CU055",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu055,
    RESERVs: [
      {
        id: "RESERV-05521",
        name: "Codjo Le Prince",
        price: 7.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO055",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 95.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do055,
    RESERVs: [
      {
        id: "RESERV-05531",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-05532",
        name: "Fabrice Du Mont",
        price: 95.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "JA055",
    name: "Jardin Dargent",
    creator: "Olivie du Bois",
    price: 54.25,
    description:
      "Le jardin des ancetres. Une representation de lheritage glorieux de ceux qui ont batti le present",
    image: assets.ja055,
    RESERVs: [
      {
        id: "RESERV-05541",
        name: "Codjo Le Prince",
        price: 56.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-05542",
        name: "Fabrice Du Mont",
        price: 54.25,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-05543",
        name: "Jackie Wong",
        price: 55.15,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-05544",
        name: "Vincent Swift",
        price: 54.15,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "PI055",
    name: "Piscine Des Orca",
    creator: "David Au Bon",
    price: 10.25,
    description:
      "La piscine du Chateau deau qui vous rappelle vos reves les plus beaux",
    image: assets.pi055,
    RESERVs: [
      {
        id: "RESERV-05551",
        name: "Codjo Le Prince",
        price: 20.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "SA055",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 20.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa055,
    RESERVs: [
      {
        id: "RESERV-61",
        name: "Codjo Le Prince",
        price: 29.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-62",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-63",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-64",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-65",
        name: "Caroline Lee",
        price: 17.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH066",
    name: "Chambre Des Grands",
    creator: "Fabien Le Patient",
    price: 58.25,
    description:
      "La chambre assortit de tous les accessoirs pour un agreable repos et haute consideration du temps passe durant tout le sejour",
    image: assets.ch066,
    RESERVs: [],
  },
  {
    id: "CU066",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu066,
    RESERVs: [
      {
        id: "RESERV-06621",
        name: "Codjo Le Prince",
        price: 97.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO066",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 195.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do066,
    RESERVs: [
      {
        id: "RESERV-06631",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-06632",
        name: "Fabrice Du Mont",
        price: 45.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "JA066",
    name: "Jardin Dargent",
    creator: "Olivie du Bois",
    price: 34.25,
    description:
      "Le jardin des ancetres. Une representation de lheritage glorieux de ceux qui ont batti le present",
    image: assets.ja066,
    RESERVs: [
      {
        id: "RESERV-06641",
        name: "Codjo Le Prince",
        price: 56.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-06642",
        name: "Fabrice Du Mont",
        price: 24.25,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-06643",
        name: "Jackie Wong",
        price: 15.15,
        image: assets.person04,
        date: "Decembre 01, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-06644",
        name: "Vincent Swift",
        price: 9.15,
        image: assets.person02,
        date: "Decembre 21, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "SA066",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 29.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa066,
    RESERVs: [
      {
        id: "RESERV-06661",
        name: "Codjo Le Prince",
        price: 39.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-06662",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-06663",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-06664",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Novembre 11, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-06665",
        name: "Caroline Lee",
        price: 37.25,
        image: assets.person02,
        date: "Decembre 17, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH077",
    name: "Chambre La Belle Etoile",
    creator: "Olive du Bois",
    price: 90.25,
    description:
      "La vie est belle. Il est bon de passer ses vacances a la BELLE.",
    image: assets.ch077,
    RESERVs: [
      {
        id: "RESERV-077",
        name: "Codjo Le Prince",
        price: 84.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-07712",
        name: "Fabrice Du Mont",
        price: 94.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-13",
        name: "Jackie Wong",
        price: 88.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CU077",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu077,
    RESERVs: [
      {
        id: "RESERV-07721",
        name: "Codjo Le Prince",
        price: 7.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO077",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 95.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do077,
    RESERVs: [
      {
        id: "RESERV-07731",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-07732",
        name: "Fabrice Du Mont",
        price: 95.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "JA077",
    name: "Jardin Dargent",
    creator: "Olivie du Bois",
    price: 54.25,
    description:
      "Le jardin des ancetres. Une representation de lheritage glorieux de ceux qui ont batti le present",
    image: assets.ja077,
    RESERVs: [
      {
        id: "RESERV-07741",
        name: "Codjo Le Prince",
        price: 56.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-07742",
        name: "Fabrice Du Mont",
        price: 54.25,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-07743",
        name: "Jackie Wong",
        price: 55.15,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-07744",
        name: "Vincent Swift",
        price: 54.15,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "SA077",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 20.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa077,
    RESERVs: [
      {
        id: "RESERV-07761",
        name: "Codjo Le Prince",
        price: 29.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-07762",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-07763",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-07764",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-07765",
        name: "Caroline Lee",
        price: 17.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH088",
    name: "Chambre Des Grands",
    creator: "Fabien Le Patient",
    price: 58.25,
    description:
      "La chambre assortit de tous les accessoirs pour un agreable repos et haute consideration du temps passe durant tout le sejour",
    image: assets.ch088,
    RESERVs: [],
  },
  {
    id: "CU088",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu088,
    RESERVs: [
      {
        id: "RESERV-08821",
        name: "Codjo Le Prince",
        price: 97.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO088",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 195.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do088,
    RESERVs: [
      {
        id: "RESERV-08831",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-08832",
        name: "Fabrice Du Mont",
        price: 45.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "JA088",
    name: "Jardin Dargent",
    creator: "Olivie du Bois",
    price: 34.25,
    description:
      "Le jardin des ancetres. Une representation de lheritage glorieux de ceux qui ont batti le present",
    image: assets.ja088,
    RESERVs: [
      {
        id: "RESERV-08841",
        name: "Codjo Le Prince",
        price: 56.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-08842",
        name: "Fabrice Du Mont",
        price: 24.25,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-08843",
        name: "Jackie Wong",
        price: 15.15,
        image: assets.person04,
        date: "Decembre 01, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-08844",
        name: "Vincent Swift",
        price: 9.15,
        image: assets.person02,
        date: "Decembre 21, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "SA088",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 29.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa088,
    RESERVs: [
      {
        id: "RESERV-08861",
        name: "Codjo Le Prince",
        price: 39.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-08862",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-08863",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-08864",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Novembre 11, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-08865",
        name: "Caroline Lee",
        price: 37.25,
        image: assets.person02,
        date: "Decembre 17, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH099",
    name: "Chambre La Belle Etoile",
    creator: "Olive du Bois",
    price: 90.25,
    description:
      "La vie est belle. Il est bon de passer ses vacances a la BELLE.",
    image: assets.ch099,
    RESERVs: [
      {
        id: "RESERV-099",
        name: "Codjo Le Prince",
        price: 84.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-09912",
        name: "Fabrice Du Mont",
        price: 94.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-13",
        name: "Jackie Wong",
        price: 88.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CU099",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu099,
    RESERVs: [
      {
        id: "RESERV-09921",
        name: "Codjo Le Prince",
        price: 7.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO099",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 95.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do099,
    RESERVs: [
      {
        id: "RESERV-09931",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-09932",
        name: "Fabrice Du Mont",
        price: 95.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "JA099",
    name: "Jardin Dargent",
    creator: "Olivie du Bois",
    price: 54.25,
    description:
      "Le jardin des ancetres. Une representation de lheritage glorieux de ceux qui ont batti le present",
    image: assets.ja099,
    RESERVs: [
      {
        id: "RESERV-09941",
        name: "Codjo Le Prince",
        price: 56.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-42",
        name: "Fabrice Du Mont",
        price: 54.25,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-43",
        name: "Jackie Wong",
        price: 55.15,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-44",
        name: "Vincent Swift",
        price: 54.15,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "SA099",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 20.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa099,
    RESERVs: [
      {
        id: "RESERV-61",
        name: "Codjo Le Prince",
        price: 29.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-62",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-63",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-64",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-65",
        name: "Caroline Lee",
        price: 17.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH100",
    name: "Chambre Des Grands",
    creator: "Fabien Le Patient",
    price: 58.25,
    description:
      "La chambre assortit de tous les accessoirs pour un agreable repos et haute consideration du temps passe durant tout le sejour",
    image: assets.ch100,
    RESERVs: [],
  },
  {
    id: "CU100",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu100,
    RESERVs: [
      {
        id: "RESERV-10021",
        name: "Codjo Le Prince",
        price: 97.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO100",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 195.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do100,
    RESERVs: [
      {
        id: "RESERV-10031",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-10032",
        name: "Fabrice Du Mont",
        price: 45.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "SA100",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 29.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa100,
    RESERVs: [
      {
        id: "RESERV-61",
        name: "Codjo Le Prince",
        price: 39.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-62",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-63",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-64",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Novembre 11, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-65",
        name: "Caroline Lee",
        price: 37.25,
        image: assets.person02,
        date: "Decembre 17, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH101",
    name: "Chambre La Belle Etoile",
    creator: "Olive du Bois",
    price: 90.25,
    description:
      "La vie est belle. Il est bon de passer ses vacances a la BELLE.",
    image: assets.ch101,
    RESERVs: [
      {
        id: "RESERV-101",
        name: "Codjo Le Prince",
        price: 84.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-102",
        name: "Fabrice Du Mont",
        price: 94.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-13",
        name: "Jackie Wong",
        price: 88.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CU101",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu101,
    RESERVs: [
      {
        id: "RESERV-10121",
        name: "Codjo Le Prince",
        price: 7.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO101",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 95.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do101,
    RESERVs: [
      {
        id: "RESERV-10131",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-10132",
        name: "Fabrice Du Mont",
        price: 95.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "SA101",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 20.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa101,
    RESERVs: [
      {
        id: "RESERV-61",
        name: "Codjo Le Prince",
        price: 29.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-62",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-63",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-64",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-65",
        name: "Caroline Lee",
        price: 17.25,
        image: assets.person02,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH102",
    name: "Chambre Des Grands",
    creator: "Fabien Le Patient",
    price: 58.25,
    description:
      "La chambre assortit de tous les accessoirs pour un agreable repos et haute consideration du temps passe durant tout le sejour",
    image: assets.ch102,
    RESERVs: [],
  },
  {
    id: "CU102",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu102,
    RESERVs: [
      {
        id: "RESERV-10221",
        name: "Codjo Le Prince",
        price: 97.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO102",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 195.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do102,
    RESERVs: [
      {
        id: "RESERV-10231",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-10232",
        name: "Fabrice Du Mont",
        price: 45.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "SA102",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 29.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa102,
    RESERVs: [
      {
        id: "RESERV-61",
        name: "Codjo Le Prince",
        price: 39.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-62",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-63",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-64",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Novembre 11, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-65",
        name: "Caroline Lee",
        price: 37.25,
        image: assets.person02,
        date: "Decembre 17, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH103",
    name: "Chambre Des Grands",
    creator: "Fabien Le Patient",
    price: 58.25,
    description:
      "La chambre assortit de tous les accessoirs pour un agreable repos et haute consideration du temps passe durant tout le sejour",
    image: assets.ch103,
    RESERVs: [],
  },
  {
    id: "CU103",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu103,
    RESERVs: [
      {
        id: "RESERV-10321",
        name: "Codjo Le Prince",
        price: 97.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO103",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 195.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do103,
    RESERVs: [
      {
        id: "RESERV-10331",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-10332",
        name: "Fabrice Du Mont",
        price: 45.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "SA103",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 29.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa103,
    RESERVs: [
      {
        id: "RESERV-61",
        name: "Codjo Le Prince",
        price: 39.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-62",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-63",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-64",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Novembre 11, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-65",
        name: "Caroline Lee",
        price: 37.25,
        image: assets.person02,
        date: "Decembre 17, 2023 a 3:50 PM",
      },
    ],
  },
  {
    id: "CH104",
    name: "Chambre Des Grands",
    creator: "Fabien Le Patient",
    price: 58.25,
    description:
      "La chambre assortit de tous les accessoirs pour un agreable repos et haute consideration du temps passe durant tout le sejour",
    image: assets.ch104,
    RESERVs: [],
  },
  {
    id: "CU104",
    name: "Cuisine De la Cave",
    creator: "Dossou Du Bois",
    price: 104.25,
    description:
      "La cuisine de mes reves. Tous les repas sont chaud bouyant",
    image: assets.cu104,
    RESERVs: [
      {
        id: "RESERV-10421",
        name: "Codjo Le Prince",
        price: 97.05,
        image: assets.person04,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
    ],
  },
  {
    id: "DO104",
    name: "Douche Du Roi ",
    creator: "Midouwe Patricia",
    price: 195.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.do104,
    RESERVs: [
      {
        id: "RESERV-10431",
        name: "Codjo Le Prince",
        price: 95.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-10432",
        name: "Fabrice Du Mont",
        price: 45.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
    ],
  },
  {
    id: "SA104",
    name: "Salon du Desir",
    creator: "Apkan Le Froid",
    price: 29.25,
    description:
      "Des moments ou se cree des rencontre inoubliable dans nos salons de renommer et standing internationaux. Pour ton plaisir sans limite, rejoint les grands au Salon.",
    image: assets.sa104,
    RESERVs: [
      {
        id: "RESERV-61",
        name: "Codjo Le Prince",
        price: 39.25,
        image: assets.person02,
        date: "Decembre 12, 2023 a 12:10 PM",
      },
      {
        id: "RESERV-62",
        name: "Fabrice Du Mont",
        price: 35.5,
        image: assets.person03,
        date: "Decembre 27, 2023 a 1:50 PM",
      },
      {
        id: "RESERV-63",
        name: "Jackie Wong",
        price: 19.75,
        image: assets.person04,
        date: "Decembre 31, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-64",
        name: "Dossou Du Bois",
        price: 21.25,
        image: assets.person02,
        date: "Novembre 11, 2023 a 3:50 PM",
      },
      {
        id: "RESERV-65",
        name: "Caroline Lee",
        price: 37.25,
        image: assets.person02,
        date: "Decembre 17, 2023 a 3:50 PM",
      },
    ],
  },
];

export { NFTData };
